name: Build and Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x  # Change this to match your desired .NET version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release

    - name: Publish project
      run: dotnet publish -c Release -o publish

    - name: Copy published files to Nginx directory
      run: |
        sudo systemctl stop nginx
        if [ -d "publish" ]; then
            sudo cp -r publish/* /usr/share/nginx/html
        else
            echo "Error: Publish directory not found."
            exit 1
        fi
        sudo systemctl start nginx

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          host: 18.119.167.40
          username: ec2-user
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22  # Default SSH port
          script: |
            cd /path/to/your/app
            git pull
            dotnet build
            dotnet run
